---
title: "Conservation Efforts by State"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(urbnmapr)


conservation <- readRDS("states_es_laws.rds", refhook = NULL)
```

Column {data-width=650}
-----------------------------------------------------------------------

### State Total Scores and Ranks

On the chart below, we see how each state ranks in their conservation efforts. 

Each state is represented alone on the Y axis. Each state's respective distance from that axis represents their `total conservation score`.

Unsurprisingly, states' total score is closely linked with their overall rank (represented in varying shades of blue). The darker the shade of blue, the better that state ranks amongst its peers. 

```{r fig.height = 6, fig.width = 6}
#qplot(code, data = conservation, facets = .~conserv_programs)
ggplot(data = conservation, aes(x = total, y = code, color= rank)) + 
  geom_count()

```



Column {data-width=350}  {data-height=700}
-----------------------------------------------------------------------

### Substantive Restrictions by State
```{r fig.height = 7, fig.width = 10}



state_data <- left_join(conservation, states, by = c("state" = "state_name")) 

state_data %>%
  ggplot(aes(long, lat, group = group, fill = substantive_restrictions, color=code)) +
  coord_fixed(ratio = q) +
   geom_polygon(color = "#ffffff", size = .15) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Substantive Restrictions")
```




